version: '3'

services:
  next-app:
    container_name: markdown-previewer-development
    build:
      context: ./
      dockerfile: dev.Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - ./pages:/app/pages
      - ./data:/app/data
      - ./components:/app/components
      - ./fonts:/app/fonts
      - ./images:/app/images
      - ./plugins:/app/plugins
      - ./styles:/app/styles
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network
  # Add more containers below (nginx, postgres, etc.)

  # Define a network, which allows containers to communicate
  # with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
